on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.md"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.19.3'
      - name: Format check
        run: gofmt -l .
      - name: Setup GO environment
        run: go mod download

#      - name: Setup GO environment
#        run: |
#          go mod download
#          go get -t .
#

      - name: Unit tests
        run: |
          make test
      - name: Coverage check
        env:
          TESTCOVERAGE_THRESHOLD: 7
        run: |
          echo "Quality Gate: checking test coverage is above threshold ..."
          echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
          COVERAGE=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
          echo "Current test coverage : $COVERAGE %"
          if (( $(echo "$COVERAGE $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
              echo "OK"
          else
              echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
              echo "Failed"
              exit 1
          fi

      - name: Build
        run: make build